theme: jekyll-theme-modernist

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - notes.md 
  - links.md
  - Steps_To_Follow.md
  - index.md